package model;

import java.math.BigDecimal;
import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2021-07-06T10:29:37.049+0800")
@StaticMetamodel(MarineWater2.class)
public class MarineWater2_ {
	public static volatile SingularAttribute<MarineWater2, MarineWater2PK> id;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> airTemp;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> bod5;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> chl;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> cond;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> do_;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> doSat;
	public static volatile SingularAttribute<MarineWater2, Double> ecoli;
	public static volatile SingularAttribute<MarineWater2, Double> fc;
	public static volatile SingularAttribute<MarineWater2, String> fishKill;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> flscufa;
	public static volatile SingularAttribute<MarineWater2, String> lBod5;
	public static volatile SingularAttribute<MarineWater2, String> lChl;
	public static volatile SingularAttribute<MarineWater2, String> lEcoli;
	public static volatile SingularAttribute<MarineWater2, String> lFc;
	public static volatile SingularAttribute<MarineWater2, String> lNh4;
	public static volatile SingularAttribute<MarineWater2, String> lNo2;
	public static volatile SingularAttribute<MarineWater2, String> lNo3;
	public static volatile SingularAttribute<MarineWater2, String> lPhae;
	public static volatile SingularAttribute<MarineWater2, String> lPo4;
	public static volatile SingularAttribute<MarineWater2, String> lSio2;
	public static volatile SingularAttribute<MarineWater2, String> lSs;
	public static volatile SingularAttribute<MarineWater2, String> lTknP;
	public static volatile SingularAttribute<MarineWater2, String> lTknS;
	public static volatile SingularAttribute<MarineWater2, String> lTknSp;
	public static volatile SingularAttribute<MarineWater2, String> lTpP;
	public static volatile SingularAttribute<MarineWater2, String> lTpS;
	public static volatile SingularAttribute<MarineWater2, String> lTpSp;
	public static volatile SingularAttribute<MarineWater2, String> lTvs;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> nh3;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> nh4;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> no2;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> no3;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> par;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> phSc;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> phae;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> po4;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> sal;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> samNo;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> sd;
	public static volatile SingularAttribute<MarineWater2, String> seaCol;
	public static volatile SingularAttribute<MarineWater2, String> seaCond;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> sio2;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> solRad;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> ss;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> stime;
	public static volatile SingularAttribute<MarineWater2, String> subzone;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> temper;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> tin;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> tknP;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> tknS;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> tknSp;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> tn;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> tpP;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> tpS;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> tpSp;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> turbSc;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> tvs;
	public static volatile SingularAttribute<MarineWater2, String> wcz;
	public static volatile SingularAttribute<MarineWater2, String> weather;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> windDir;
	public static volatile SingularAttribute<MarineWater2, BigDecimal> windSp;
	public static volatile SingularAttribute<MarineWater2, String> zone;
}
