package model;

import java.math.BigDecimal;
import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2021-07-06T10:29:37.047+0800")
@StaticMetamodel(MarineWater1.class)
public class MarineWater1_ {
	public static volatile SingularAttribute<MarineWater1, MarineWater1PK> id;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> airTemp;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> bod5;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> chl;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> cond;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> do_;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> doSat;
	public static volatile SingularAttribute<MarineWater1, Double> ecoli;
	public static volatile SingularAttribute<MarineWater1, Double> fc;
	public static volatile SingularAttribute<MarineWater1, String> fishKill;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> flscufa;
	public static volatile SingularAttribute<MarineWater1, String> lBod5;
	public static volatile SingularAttribute<MarineWater1, String> lChl;
	public static volatile SingularAttribute<MarineWater1, String> lEcoli;
	public static volatile SingularAttribute<MarineWater1, String> lFc;
	public static volatile SingularAttribute<MarineWater1, String> lNh4;
	public static volatile SingularAttribute<MarineWater1, String> lNo2;
	public static volatile SingularAttribute<MarineWater1, String> lNo3;
	public static volatile SingularAttribute<MarineWater1, String> lPhM;
	public static volatile SingularAttribute<MarineWater1, String> lPhae;
	public static volatile SingularAttribute<MarineWater1, String> lPo4;
	public static volatile SingularAttribute<MarineWater1, String> lSio2;
	public static volatile SingularAttribute<MarineWater1, String> lSs;
	public static volatile SingularAttribute<MarineWater1, String> lTknP;
	public static volatile SingularAttribute<MarineWater1, String> lTknS;
	public static volatile SingularAttribute<MarineWater1, String> lTknSp;
	public static volatile SingularAttribute<MarineWater1, String> lTpP;
	public static volatile SingularAttribute<MarineWater1, String> lTpS;
	public static volatile SingularAttribute<MarineWater1, String> lTpSp;
	public static volatile SingularAttribute<MarineWater1, String> lTurbM;
	public static volatile SingularAttribute<MarineWater1, String> lTvs;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> nh3;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> nh4;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> nh4Nm;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> no2;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> no2Nm;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> no3;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> no3Nm;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> noxNm;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> par;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> phM;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> phSc;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> phae;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> po4;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> po4Pm;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> sal;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> samNo;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> sd;
	public static volatile SingularAttribute<MarineWater1, String> seaCol;
	public static volatile SingularAttribute<MarineWater1, String> seaCond;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> sio2;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> solRad;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> ss;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> stime;
	public static volatile SingularAttribute<MarineWater1, String> subzone;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> temper;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tin;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tinNm;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tinPo4Mmr;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tknNm;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tknP;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tknS;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tknSp;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tn;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tnNm;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tnTpMmr;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tpP;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tpPm;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tpS;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tpSp;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> turbM;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> turbSc;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> tvs;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> viewNo;
	public static volatile SingularAttribute<MarineWater1, String> wcz;
	public static volatile SingularAttribute<MarineWater1, String> weather;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> windDir;
	public static volatile SingularAttribute<MarineWater1, BigDecimal> windSp;
	public static volatile SingularAttribute<MarineWater1, String> zone;
}
